default_folder: C:\Users\andre\Desktop\sputofy_songs
last_position:
  xPos: 108
  yPos: 115
last_window_size:
  heigth: 540
  width: 938
playlistList:
  Aniume:
  - C:/Users/andre/Desktop/Anime/Akame Ga kill OP 2 Liar Mask Full.mp3
  - C:/Users/andre/Desktop/Anime/akame ga kill Opening 1 [Full].mp3
  - "C:/Users/andre/Desktop/Anime/Anata no Eranda Kono Toki wo - Kanako It\u014D -\
    \ Steins;Gate - fuka ry\u014Diki no d\xE9j\xE0 vu - Opening.mp3"
  - "C:/Users/andre/Desktop/Anime/Attack on Titan - Opening 5 Full\u300EShoukei to\
    \ Shikabane no Michi\u300Fby Linked Horizon.mp3"
  - C:/Users/andre/Desktop/Anime/Attack on Titan Season 2 - Official Opening Song
    - Shinzou wo Sasageyo by Linked Horizon.mp3
  - C:/Users/andre/Desktop/Anime/Attack on Titan Season 3 - Official Opening _ OP1
    [ RED SWAN ].mp3
  - "C:/Users/andre/Desktop/Anime/Attack on Titan \u2013 Opening Theme 2 \u2013 Jiyuu\
    \ no Tsubasa.mp3"
  - C:/Users/andre/Desktop/Anime/BLESS YoUr NAME - ChouCho (Highschool DXD BorN OP
    Full).mp3
  - "C:/Users/andre/Desktop/Anime/DARLING in the FRANXX \u2013 Opening Theme \u2013\
    \ KISS OF DEATH.mp3"
  - "C:/Users/andre/Desktop/Anime/Death Parade \u2013 Opening Theme \u2013 Flyers.mp3"
  - C:/Users/andre/Desktop/Anime/High School DXD Hero Opening Theme - Switch.mp3
  - C:/Users/andre/Desktop/Anime/Highschool DxD New OP 2 [FULL].mp3
  - C:/Users/andre/Desktop/Anime/Highschool DxD Season 2 Theme Song With Lyrics.mp3
  - C:/Users/andre/Desktop/Anime/Kaguya-sama - Love is War OP  - Love Dramatic _ Masayuki
    Suzuki (Lyrics).mp3
  - "C:/Users/andre/Desktop/Anime/Kaguya-sama - Love is War Season 2 - Opening Full\u300E\
    DADDY! DADDY! DO!\u300Fby Masayuki Suzuki.mp3"
  - C:/Users/andre/Desktop/Anime/Kakegurui xx OP _ Kakegurui Season 2 Opening HD.mp3
  - C:/Users/andre/Desktop/Anime/kenzen robo daimidaler opening full.mp3
  - C:/Users/andre/Desktop/Anime/KONOSUBA -God's blessing on this wonderful world!
    - Opening _ Fantastic Dreamer.mp3
  - C:/Users/andre/Desktop/Anime/KONOSUBA -God's blessing on this wonderful world!
    2 - Opening _ Tomorrow.mp3
  - "C:/Users/andre/Desktop/Anime/Nanatsu no Taizai OP Full \u300EIkimonogakari -\
    \ Netsujou no Spectrum\u300F \u3010AMV Lyrics\u3011.mp3"
  - C:/Users/andre/Desktop/Anime/No Game No Life Opening Full.mp3
  - C:/Users/andre/Desktop/Anime/Noragami Aragoto - Official Opening - Kyouran Hey
    Kids!!.mp3
  - C:/Users/andre/Desktop/Anime/Opening Rakudai kishi no cavalry [ -identidy full-
    ].mp3
  - "C:/Users/andre/Desktop/Anime/Rakudai Kishi no Cavalry ED \u843D\u7B2C\u9A0E\u58EB\
    \u306E\u82F1\u96C4\u8B5A\uFF08\u30AD\u30E3\u30D0\u30EB\u30EA\u30A3\uFF09ED \u3010\
    HD\u3011 60 FPS.mp3"
  - C:/Users/andre/Desktop/Anime/Seishun Buta Yarou wa Bunny Girl Senpai no Yume wo
    Minai OP - Kimi no Sei _ the peggies.mp3
  - C:/Users/andre/Desktop/Anime/Shingeki No Kyojin Opening 1 [With Lyrics].mp3
  - C:/Users/andre/Desktop/Anime/Shinmai Maou no Testament Burst OP Full.mp3
  - "C:/Users/andre/Desktop/Anime/STEINS;GATE - The Movie - Load Region of D\xE9j\xE0\
    \ vu Ending - 'Itsumo Kono Basho de' - Ayane [ENG LYRICS].mp3"
  - C:/Users/andre/Desktop/Anime/Steins;Gate Opening Theme - Hacking to the Gate (Full
    Version).mp3
  - C:/Users/andre/Desktop/Anime/The Testament Of Sister New Devil - Opening Full.mp3
  - C:/Users/andre/Desktop/Anime/Yasuharu Takanashi Fairy Tail Main Theme.mp3
  - C:/Users/andre/Desktop/Anime/Youkoso Jitsuryoku Shijou Shugi no Kyoushitsu e OP
    Full+ _LYRICS.mp3
  - "C:/Users/andre/Desktop/Anime/[MAD]\u30CF\u30A4\u30B9\u30AF\u30FC\u30EBD\xD7D\
    \ OP Trip -innocent of D-[FULL] .mp3"
  - "C:/Users/andre/Desktop/Anime/\u300C\u6B8B\u9177\u306A\u5929\u4F7F\u306E\u30C6\
    \u30FC\u30BC\u300DMUSIC VIDEO\uFF08HDver.\uFF09 Zankoku na Tenshi no Te-ze\u201C\
    The Cruel Angel's Thesis\u201D.mp3"
  - "C:/Users/andre/Desktop/Anime/\u92FC\u306E\u932C\u91D1\u8853\u5E2B OP _ Fullmetal\
    \ Alchemist - Brotherhood OP5 - Rain - SID.mp3"
volume: 100
