default_folder: C:\Users\andre\Desktop\sputofy_songs
last_position:
  xPos: 121
  yPos: 162
last_window_size:
  heigth: 554
  width: 921

playlist1Name: Steins;Gate
playlist2Name: cacca
playlist3Name: tesr2
playlist_list: []

volume: 3
