# import sys
# from PyQt5 import QtCore, QtGui, QtWidgets

# class CustomWidget(QtCore.QObject):
#     def __init__(self, parent = None):
#         super(CustomWidget, self).__init__(parent)
#         self.button = QtWidgets.QPushButton("button")
#         lay = QtWidgets.QHBoxLayout()
#         lay.addWidget(self.button)
#         lay.setContentsMargins(0,0,0,0)

# class Dialog(QtWidgets.QDialog):
#     def __init__(self, parent=None):
#         super(Dialog, self).__init__(parent=parent)
#         vLayout = QtWidgets.QVBoxLayout(self)
#         hLayout = QtWidgets.QHBoxLayout()
#         self.lineEdit = QtWidgets.QLineEdit()
#         hLayout.addWidget(self.lineEdit)
#         self.filter = QtWidgets.QPushButton("cacca", self)
#         hLayout.addWidget(self.filter)
#         self.list = QtWidgets.QListView(self)
#         vLayout.addLayout(hLayout)
#         vLayout.addWidget(self.list)

#         self.model = QtGui.QStandardItemModel(self.list)
#         codes = [
#             'cacca',
#             'windows'
#         ]
#         self.list.setModel(self.model)
#         for code in codes:
#             item = QtGui.QStandardItem(code)
#             self.model.appendRow(item)
#             self.list.setIndexWidget(item.index(), CustomWidget())

# if __name__ == "__main__":
#     app = QtWidgets.QApplication(sys.argv)
#     w = Dialog()
#     w.show()
#     sys.exit(app.exec_())

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class MyCustomWidget(QtWidgets.QWidget):
    def __init__(self, name,  parent=None):
        super(MyCustomWidget, self).__init__(parent)

        self.row = QtWidgets.QHBoxLayout()

        self.row.addWidget(QtWidgets.QLabel(name))
        self.row.addWidget(QtWidgets.QPushButton("view"))

        self.setLayout(self.row)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.listView = QtWidgets.QListWidget(Form)
        self.listView.setObjectName("listView")
        self.gridLayout.addWidget(self.listView, 0, 0, 1, 1)

        item = QtWidgets.QListWidgetItem(self.listView)
        self.listView.addItem(item)

        lista = ['cacca', 'popo']
        for oggetto in lista:
            row = MyCustomWidget(oggetto)
            item.setSizeHint(row.minimumSizeHint())

            self.listView.setItemWidget(item, row)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
