# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'playlistName.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_playlistNameWindow(object):
    def setupUi(self, playlistNameWindow):
        playlistNameWindow.setObjectName("playlistNameWindow")
        playlistNameWindow.resize(288, 121)
        
        self.gridLayout_2 = QtWidgets.QGridLayout(playlistNameWindow)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setVerticalSpacing(13)
        self.gridLayout.setObjectName("gridLayout")
        
        
        self.playlistNameLabel = QtWidgets.QLabel(playlistNameWindow)
        self.playlistNameLabel.setObjectName("playlistNamelabel")
        self.gridLayout.addWidget(self.playlistNameLabel, 0, 0, 1, 1)
        
        
        self.playlistLineEdit = QtWidgets.QLineEdit(playlistNameWindow)
        self.playlistLineEdit.setObjectName("playlistLineEdit")
        self.gridLayout.addWidget(self.playlistLineEdit, 1, 0, 1, 2)
        
        
        self.OKBtn = QtWidgets.QPushButton(playlistNameWindow)
        self.OKBtn.setObjectName("OKBtn")
        self.gridLayout.addWidget(self.OKBtn, 2, 0, 1, 1)
        
        
        self.CancelBtn = QtWidgets.QPushButton(playlistNameWindow)
        self.CancelBtn.setObjectName("CancelBtn")
        self.gridLayout.addWidget(self.CancelBtn, 2, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(playlistNameWindow)
        QtCore.QMetaObject.connectSlotsByName(playlistNameWindow)

    def retranslateUi(self, playlistNameWindow):
        _translate = QtCore.QCoreApplication.translate
        playlistNameWindow.setWindowTitle(_translate("playlistNameWindow", "Dialog"))
        self.playlistNameLabel.setText(_translate("playlistNameWindow", "save playlist 1 as:"))
        self.OKBtn.setText(_translate("playlistNameWindow", "OK"))
        self.CancelBtn.setText(_translate("playlistNameWindow", "Cancel"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     playlistNameWindow = QtWidgets.QDialog()
#     ui = Ui_playlistNameWindow()
#     ui.setupUi(playlistNameWindow)
#     playlistNameWindow.show()
#     sys.exit(app.exec_())
